spring.application.name=hello-spring

# WebSocket ??
spring.websocket.path=/ws

# MongoDB ??
spring.data.mongodb.uri=mongodb://localhost:27017/boarddb
spring.data.mongodb.database=WebChatting

# MySQL ??
spring.datasource.url=jdbc:mysql://localhost:3306/WebChattingDB
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate ?? (JPA ??)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
